//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingAgent
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtg_user_meeting_rel
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public int meeting_id { get; set; }
        public Nullable<int> status_id { get; set; }
    }
}
