//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingAgent
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_meeting
    {
        public int RelId { get; set; }
        public int meeting_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public Nullable<System.TimeSpan> MeetingEndHour { get; set; }
        public Nullable<System.TimeSpan> MeetingStartHour { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_user { get; set; }
        public string place { get; set; }
        public bool is_active { get; set; }
        public string PhoneNumber { get; set; }

        public bool IsApproved { get; set; }
        public bool IsRejected { get; set; }
    }
}
